# Generated by Django 6.0.2 on 2026-03-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='total_price',
            field=models.FloatField(editable=False),
        ),
    ]
