# Generated by Django 6.0.2 on 2026-04-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0003_alter_sell_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
