# Generated by Django 6.0.2 on 2026-05-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
